#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:latest
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"

  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/:/etc/hyperledger/crypto/peer
        - ../mount/peer0.org3.example.com/var/hyperledger/production:/var/hyperledger/production
    depends_on:
        - couchdb3
#    extra_hosts:
#        - "orderer1.example.com:172.16.10.18"
#        - "orderer2.example.com:172.16.10.18"
